#!/bin/bash

#PBS -m abe
#PBS -q standard

cd ${HOME}/micro/cahn-hilliard-3d

make clean
make run geo=${geo} problem=${problem}
make remote-video host="urbain@155.198.212.223" geo=${geo} problem=${problem}
