#!/bin/bash

#PBS -N ch3d
#PBS -m abe
#PBS -q standard

cd ${HOME}/micro/chns3D
rm -f ch3d.*
make clean-all

make batch-install geo=cube problem=injection && make mesh
make batch-install geo=cube problem=droplets && make mesh
make batch-install geo=cube problem=droplet && make mesh
make batch-install geo=cube problem=droplet-solid && make mesh
make batch-install geo=cube problem=flat && make mesh

make batch-install geo=cube problem=injection
make run &
sleep 20

make batch-install geo=cube problem=droplets
make run &
sleep 20

make batch-install geo=cube problem=droplet
make run &
sleep 20

make batch-install geo=cube problem=droplet-solid
make run &
sleep 20

make batch-install geo=cube problem=flat
make run &
wait
