#!/bin/bash

#PBS -m abe
#PBS -q huxley_standard

cd ${HOME}/micro/cahn-hilliard

make clean;
make remote-mesh host="urbain@155.198.212.223" problem=${problem};
make run problem=${problem};
make remote-video host="urbain@155.198.212.223" problem=${problem}
