#!/usr/bin/env bash
values="1e2 1e3"
for Pe in ${values}; do
    for Ca in ${values}; do
        directory="Pe=${Pe}/Ca=${Ca}"
        mkdir -p ${directory}
        ln -sf ${PWD}/channel.geo ${directory}/channel.geo
        ln -sf ${PWD}/problem.pde ${directory}/problem.pde
        ln -sf ${PWD}/config.mk   ${directory}/config.mk
        echo -e "Pe=${Pe};\nCa=${Ca};" > ${directory}/parameters.pde
    done
done
