#define SOLVER_TIME_ADAPTATION
#define SOLVER_TIME_ADAPTATION_METHOD AYMARD
#define SOLVER_TIME_ADAPTATION_FACTOR sqrt(2)

#if SOLVER_TIME_ADAPTATION_METHOD == GUILLEN
#define SOLVER_TIME_ADAPTATION_TOL_MIN 1
#define SOLVER_TIME_ADAPTATION_TOL_MAX 100
#endif

#define SOLVER_TIME_ADAPTATION_DT_OVER_PE_MIN 0
#define SOLVER_TIME_ADAPTATION_DT_OVER_PE_MAX (SOLVER_DT/Pe)*SOLVER_TIME_ADAPTATION_FACTOR^8*0.99
